### ISSUE TITLE
Add this to libphonenumber package

### ISSUE THREAD

**Issue by cedvdb** [natintosh/plugin_libphonenumber#1]
A PR to add this directly inside the libphonenumber package would be nice

**Comment by natintosh** [comment]
This actually nice a idea. I'll see what I can do...

**Comment by cedvdb** [comment]
@natintosh, I'm writing a dart version of lib phone number. It's not a one to one mapping as currently it deals with only mobile numbers but you might be interested in it. I might make it work with all numbers eventually if needed.

I'll keep you updated
