### ISSUE TITLE
[iOS] NumberParserLibphonenumber.formatted: Failed to format phone number

### ISSUE THREAD

**Issue by aytunch** [natintosh/plugin_libphonenumber#15]
```
flutter: [DEBUG] 17:51:12 NumberParserLibphonenumber.formatted: Failed to format phone number: +12124444444, isoCode null
flutter: Exception: PlatformException(1, The country code is invalid., null, null)
```
Hi @natintosh :)
On iOS I am getting this error. When I was using `libphonenumber:` I did not get any problems. Now I changed to `libphonenumber_plugin` because I use iOS & Android & Web.
I pinponted the problem to this:
<img width="700" alt="Screenshot 2023-02-26 at 17 54 18" src="https://user-images.githubusercontent.com/6442915/221418110-abedbfd2-d003-4648-9324-923a6682eaa1.png">

**Comment by natintosh** [comment]
Hi @aytunch... 

Thanks for reaching out. I'll be pushing an update later today that fixes this.

**Comment by aytunch** [comment]
Ogunye, it would be awesome. I have been struggling for the past 2 days since I changed plugins. Would you be so kind to notify this post so I can give it a try? Thanks

**Comment by aytunch** [comment]
Thanks for the quick fix @natintosh 
But I still get an exception at the exact same place
Debugger throws an exception and never enters line 36
<img width="717" alt="Screenshot 2023-02-27 at 18 11 48" src="https://user-images.githubusercontent.com/6442915/221601801-285eaa35-6bba-437a-a18c-c8a1b45141e3.png">

**Comment by natintosh** [comment]
Hi @aytunch 

I reviewed what you sent and I observed that there was a mistake with how you are young the package

So apparently `EN` **is not a country iso code but a country language iso code**. 


<img width="1440" alt="Screenshot 2023-02-27 at 18 26 45" src="https://user-images.githubusercontent.com/27495055/221637045-0344700f-060b-40b1-997b-af7c7cba5337.png">

<img width="1440" alt="Screenshot 2023-02-27 at 18 23 47" src="https://user-images.githubusercontent.com/27495055/221635782-d3a319d4-8873-414e-b0ab-4325452cdfa3.png">

<img width="1440" alt="Screenshot 2023-02-27 at 18 26 23" src="https://user-images.githubusercontent.com/27495055/221636882-7e7c01a0-4713-46fc-8b2b-a57d4c19feac.png">

You can view the list [here](https://www.iban.com/country-codes) for a list of country iso codes. Then, if you don't have access to the country iso code you can pass in an empty string.

**Comment by aytunch** [comment]
Thank you for the detailed answer. I will try to use the new `getAllCountries`
The interesting part is, I am using the exact same code I used in `libphonenumber` plugin, and just changed it to `libphonenumber_plugin`. I thougth the API and the internal workings would be same. So I mean, when I supply `US` in to `libphonenumber`, it still does not throw an exception.

I will be debugging some more. Thank you brother.

**Comment by aytunch** [comment]
@natintosh I confirmed your findings above.
on iOS I use `Platform.localeName` which returns just `EN`
on Web I use `ui.window.locale.countryCode` which returns `US`
And when we give these values to `getRegionInfo`, I get an exception in iOS.
So if your plugin can check if the isoCode is not recognized and act accordingly without throwing that would be awesome :)
Thanks again for this awesome plugin.

**Comment by natintosh** [comment]
Yeah... I'll do that. A user also faced a similar issue with my other package. I guess it has to do with the changes I made on iOS. I had to move away from an iOS package because I haven't had any updates for like 2 years now

**Comment by aytunch** [comment]
@natintosh works as expected on iOS with `^0.3.1`
Thank you very much

**Comment by aytunch** [comment]
@natintosh what is meant here in the documentation? Are you suggesting using `libphonenumber` instead for iOS and Android? Or is there a typo?

> Also For Stable Android and iOS implementation use [libphonenumber](https://pub.dev/packages/libphonenumber), since it was inspired by and has similar implementation with [libphonenumber](https://pub.dev/packages/libphonenumber).
