### ISSUE TITLE
Publish Null safe version to pub

### ISSUE THREAD

**Issue by pr-1** [natintosh/plugin_libphonenumber#2]

**Comment by pr-1** [comment]
Need to publish this package to pub for upgrading intl_phone_number_input

**Comment by pr-1** [comment]
> Need to publish this package to pub for upgrading intl_phone_number_input

or remove the ../ path and use git path so that intl_phone_number_input can be migrated. We can change that later when this one is published to pub

@natintosh 
Any thoughts on this ?

**Comment by natintosh** [comment]
I'm sorry about that. There's still a lot of work to be done on this repo (bugs on the iOS part). I'll push an update as soon as I'm able to.


I don't use a MacBook, and that's the primary cause of the hold up. If you happen to own one, I wouldn't mind working with you to try to fix the issue.

Once again I apologize for the hold up.

**Comment by pr-1** [comment]
If you need to test any mac specific things let me know I can do that for you .

**Comment by natintosh** [comment]
Alrighty 👍. 

The issue with the library on iOS is that the only method functioning is `formatAsYouType`, while the rest are either returning `null` or an empty string.
 
So, I was trying to build an interdependent library following this guide [interdependent-iOS#Federated-Plugin](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#ios), since an original library existing and some of the methods already exists in libphonenumber.

**Comment by pr-1** [comment]
Let's connect over a call if you're free ? Ping me on developerprince7@gmail.com

**Comment by natintosh** [comment]
I just sent you an email. Thanks for helping out

**Comment by natintosh** [comment]
@pr-1, thanks for having the meeting with me.

This is what is going to happen and what you would see after you have resolved the cocoa pod issue and opened `libphonenumber_plugin/example/ios/Runner.xcworkspace` from Xcode.


<img width="1440" alt="Screen Shot 2021-03-24 at 3 37 36 PM" src="https://user-images.githubusercontent.com/27495055/112337207-0033c600-8cbe-11eb-8dd9-bff564f037d8.png">

on the navigator panel to the left of your screen, you'll see two Folder, `Runner` and `Pods`.

The source code of the iOS platform code is located inside the `Pod` folder, with a relative path of `Development Pods/libphonenumber_plugin/../../example/ios/.symlinks/plugins/libphonenumber_plugin/Classes/SwiftLibPhoneNumberPlugin.swift`, to locate the swift code.

If you are able to run the code `../example/lib/main.dart` on an iOS device, you would notice that only `PhoneNumberUtils.asYouTypeFormatter` works, while the others return their null values respectively. As shown in the screenshot below.

<img width="1440" alt="Screen Shot 2021-03-24 at 3 49 05 PM" src="https://user-images.githubusercontent.com/27495055/112338257-f2cb0b80-8cbe-11eb-9b73-0ac839014027.png">


Whereas, if you run the same codebase on Android or Web, you will get something similar to this.

![Screenshot 2021-03-24 161611](https://user-images.githubusercontent.com/27495055/112338867-71c04400-8cbf-11eb-9606-456b7c3c3db6.png)

The printed statements are correct for each scenario.

Thanks once one.
